# Vampires
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVampireMatriarch
  name: Vampire Matriarch Role
  components:
  - type: MindRole
    antagPrototype: VampMatriarch
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: VampireMatriarchRole
  - type: RoleBriefing
    briefing: vamp-mat-briefing

- type: entity
  parent: MindRoleGhostRoleTeamAntagonistFlock
  id: MindRoleVampire
  name: Vampire Role
  components:
  - type: MindRole
    antagPrototype: Vamp
    exclusiveAntag: true
  - type: VampireRole
  - type: RoleBriefing
    briefing: vamp-briefing
